In [1]:
import numpy

In [2]:
import numpy as np # Mostly used

In [3]:
import numpy as aayush # can be anything

In [5]:
import numpy as 1a # need valid name

SyntaxError: invalid syntax (<ipython-input-5-aa1b9c0c7bfa>, line 1)

In [6]:
distance=[45,50,60]
speed=[5,10,7]

In [7]:
time= distance /speed

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [9]:
time=[]
for i,j in zip(distance,speed):
    time.append(i/j)

In [10]:
time

[9.0, 5.0, 8.571428571428571]

In [11]:
time=[]
for i in range(3):
    time.append(distance[i]/speed[i])

In [12]:
time

[9.0, 5.0, 8.571428571428571]

In [13]:
# How we have overcome the prior challenge using 
dist = np.array(distance)
spd = np.array(speed)

In [14]:
time=dist/speed

In [15]:
time

array([9.        , 5.        , 8.57142857])

In [16]:
x=np.array([1,2,3])

In [17]:
type(x)

numpy.ndarray

In [18]:
y=[1,2,3]

In [19]:
type(y)

list

In [20]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [21]:
x*y

array([ 4, 10, 18])

In [22]:
x/y

array([0.25, 0.4 , 0.5 ])

In [23]:
x=np.array([1,2,3])
y=np.array([4,5])

In [24]:
x/y

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [25]:
x*y

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [26]:
x+y

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [33]:
np.arange?

In [32]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(1,10,3)

array([1, 4, 7])

In [36]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [40]:
np.linspace(1,50,50) # equally spaced values

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [38]:
3.02040816-1

2.02040816

In [39]:
91.91836735-89.89795918

2.020408169999996

In [41]:
print('********* Data Array *********')
data = np.array((32,45,123,756,23,2123))    # Think of this as items in an array structure row-wise
print (data)
print('Shape: ',data.shape)
print('Type: ',data.dtype)
print('Size: ',data.size)
print('Dimension: ',data.ndim)

********* Data Array *********
[  32   45  123  756   23 2123]
Shape:  (6,)
Type:  int32
Size:  6
Dimension:  1


In [42]:
print('********* Data2 Array *********')
data2 = np.array([(1,2,3,4),(5,6,7,8)])    # Think of this as items in a 2D array structure row & column wise
print (data2)
print('Shape: ',data2.shape)
print('Type: ',data2.dtype)
print('Size: ',data2.size)
print('Dimension: ',data2.ndim)

********* Data2 Array *********
[[1 2 3 4]
 [5 6 7 8]]
Shape:  (2, 4)
Type:  int32
Size:  8
Dimension:  2


In [43]:
a=np.arange(16)

In [44]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [45]:
print (a)
print('Shape: ',a.shape)
print('Type: ',a.dtype)
print('Size: ',a.size)
print('Dimension: ',a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Shape:  (16,)
Type:  int32
Size:  16
Dimension:  1


In [47]:
b=a.reshape(4,4)

In [48]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
b.ndim

2

In [50]:
b.shape

(4, 4)

In [51]:
a.reshape(5,5)

ValueError: cannot reshape array of size 16 into shape (5,5)

In [54]:
d=a.reshape(1,1,1,1,1,1,1,16)

In [55]:
type(d)

numpy.ndarray

In [56]:
d

array([[[[[[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
              13, 14, 15]]]]]]]])

In [58]:
d.shape

(1, 1, 1, 1, 1, 1, 1, 16)

In [57]:
w

8

In [59]:
len(d.shape)

8

In [60]:
d

array([[[[[[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
              13, 14, 15]]]]]]]])

In [61]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
# the element 13, how can i do that?

In [63]:
b[3][1]

13

In [64]:
b[3,1]

13

In [ ]:
# Creat