In [1]:
import numpy as np

In [2]:
a=np.arange(16)

In [3]:
b=a.reshape(4,4)

In [4]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
b[3][1]

13

In [7]:
b[3,1]

13

In [8]:
b[-1][-3]

13

In [9]:
b[-1,-3]

13

#### Creating vs Initializing an array

In [11]:
c=np.array([])

In [13]:
c=b.copy()

In [14]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
lt=[1,2,3,"Aayush",True,False]

In [17]:
d=np.array(lt)

In [20]:
type(d[-1])

numpy.str_

In [21]:
type(lt[-1])

bool

In [22]:
d

array(['1', '2', '3', 'Aayush', 'True', 'False'], dtype='<U11')

In [24]:
lt1=[1,2,4]
e=np.array(lt1)

In [26]:
type(e[0])

numpy.int32

In [27]:
np.array(lt1,dtype=str)

array(['1', '2', '4'], dtype='<U1')

In [28]:
np.array(lt,dtype=int)

ValueError: invalid literal for int() with base 10: 'Aayush'

In [29]:
lt2=[1,2,3,True,False]
np.array(lt2,dtype=int)

array([1, 2, 3, 1, 0])

In [30]:
np.array(lt2,dtype=bool)

array([ True,  True,  True,  True, False])

In [31]:
np.array(lt,dtype=bool)

array([ True,  True,  True,  True,  True, False])

In [36]:
x=np.zeros(10).reshape(5,2)

In [40]:
type(x[0][-1])

numpy.float64

In [34]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
np.ones(10).reshape(2,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [45]:
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.diag(np.array([1,2,3,4,5,6]))

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [48]:
np.diag(np.array([1,2,3,4,5,6],dtype=float))

array([[1., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0.],
       [0., 0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 0., 6.]])

In [51]:
np.zeros(10,dtype=int).reshape(2,5)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [49]:
# Random Module

In [52]:
# return float values in half open interval of [0.0,1.0)
np.random.random((3,3))

array([[0.69035322, 0.22596025, 0.01920563],
       [0.34894053, 0.31711388, 0.20372105],
       [0.66367416, 0.51597138, 0.31616644]])

In [65]:
from numpy import random as rd

In [66]:
rd.random(10)

array([0.98466148, 0.04766649, 0.63116469, 0.12668896, 0.42613541,
       0.86796053, 0.42769511, 0.54456226, 0.81105413, 0.14266581])

In [57]:
a=np.random.random(10)
b=np.random.random((10,))

In [58]:
a == b 

array([False, False, False, False, False, False, False, False, False,
       False])

In [61]:
a.shape == b.shape

True

In [62]:
a == b # element wise comparison

array([False, False, False, False, False, False, False, False, False,
       False])

In [63]:
a


array([0.48263823, 0.9885352 , 0.0978795 , 0.85500924, 0.1794367 ,
       0.04930678, 0.4533887 , 0.4619148 , 0.29001662, 0.37977593])

In [64]:
b

array([0.19243303, 0.99497173, 0.52728441, 0.16020813, 0.31421428,
       0.28218082, 0.30725778, 0.85068139, 0.23631183, 0.27418082])

In [ ]:
np.equal()

In [67]:
# time based function seed value

In [69]:
rd.random(10)

array([0.67929579, 0.20076417, 0.2403952 , 0.85622316, 0.13237462,
       0.27935979, 0.69821405, 0.01692868, 0.88416113, 0.84206277])

In [70]:
np.random.rand(3,2)

array([[0.88788549, 0.29939778],
       [0.42640979, 0.99816009],
       [0.50185656, 0.3581732 ]])

In [71]:
np.random.rand(10)

array([0.26440814, 0.86609413, 0.74224683, 0.23667399, 0.78582588,
       0.61367839, 0.09814947, 0.67979661, 0.69517642, 0.75027593])

In [72]:
np.random.random(10)

TypeError: random() takes at most 1 positional argument (2 given)

In [73]:
np.random.randint(0,10,5)

array([5, 4, 6, 0, 3])

In [74]:
np.random.randint(0,10,50)

array([3, 2, 3, 0, 1, 5, 4, 9, 2, 8, 1, 8, 4, 2, 0, 3, 5, 5, 5, 8, 3, 9,
       9, 6, 2, 0, 3, 9, 5, 1, 9, 4, 4, 8, 9, 3, 9, 7, 1, 0, 0, 1, 0, 7,
       6, 5, 8, 4, 3, 6])

In [76]:
np.random.randint(1,7,50)

array([2, 3, 1, 4, 6, 2, 1, 5, 6, 4, 3, 6, 3, 2, 5, 3, 6, 2, 2, 4, 6, 4,
       3, 5, 4, 5, 1, 2, 1, 1, 4, 4, 6, 4, 3, 4, 5, 5, 4, 4, 2, 5, 4, 6,
       5, 4, 6, 5, 5, 6])

52 cards - Create an array for that.

10 random cards and tell me the highest steak of one particular type of card
eg

1- Hearts, A-spade,10-hearts, King-hearts, Queen- hearts

3

In [79]:
suits=['spades','clubs','hearts','diamonds']
values= list(range(1,14))

In [80]:
values

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [81]:
suits

['spades', 'clubs', 'hearts', 'diamonds']

In [86]:
cards=[]
for i in values:
    for j in suits:
        cards.append(str(i)+"_"+j)

In [89]:
samples=np.random.choice(cards,10)

In [90]:
samples

array(['1_diamonds', '6_hearts', '11_diamonds', '4_clubs', '12_spades',
       '2_diamonds', '12_hearts', '7_spades', '2_spades', '10_hearts'],
      dtype='<U11')

In [ ]:
[1,0,1,0,0,1,0,0,0,0]
a[0],a[1]

In [91]:
import random
card_points =['A','K','Q','J','2','3','4','5','6','7','8','9','10']
card_signs =['Heart','CLUB','DIAMOND','SPADE']
for i in range(10):
    random_point = random.choice(card_points,)
    random_sign = random.choice(card_signs)
    random_card = random_point,random_sign
    print(random_card)


('7', 'CLUB')
('4', 'Heart')
('4', 'DIAMOND')
('6', 'SPADE')
('9', 'Heart')
('J', 'Heart')
('9', 'CLUB')
('4', 'DIAMOND')
('4', 'SPADE')
('8', 'CLUB')


In [93]:
colors = ['heart', 'diamonds', 'spades', 'clubs']
i = 1
heart = []
diamonds = []
spades = []
clubs = []
while i <  10:
    rand_color = np.random.randint(1,5,1)
    rand_card_value = np.random.randint(1,14,1)[0]
    if rand_color == 1:
        heart.append(rand_card_value)
    elif rand_color == 2:
        diamonds.append(rand_card_value)
    elif rand_color == 3:
        spades.append(rand_card_value)
    elif rand_color == 4:
        clubs.append(rand_card_value)
    i = i+1
print ("heart values are:  ",heart)
print ("diamond values are:  ",diamonds)
print ("spades values are:  ",spades)
print ("club values are:  ",clubs)
if (len(heart) >0):
    print("Maximum heart value is: ",max(heart))
if (len(diamonds) >0):
    print("Maximum diamonds value is: ",max(diamonds))
if (len(spades) >0):
    print("Maximum spades value is: ",max(spades))
if (len(clubs) >0):
    print("Maximum clubs value is: ",max(clubs))


heart values are:   [13, 5, 8]
diamond values are:   [1, 1, 2]
spades values are:   [12]
club values are:   [7, 9]
Maximum heart value is:  13
Maximum diamonds value is:  2
Maximum spades value is:  12
Maximum clubs value is:  9


In [94]:
a

array([0.48263823, 0.9885352 , 0.0978795 , 0.85500924, 0.1794367 ,
       0.04930678, 0.4533887 , 0.4619148 , 0.29001662, 0.37977593])

In [95]:
a+10

array([10.48263823, 10.9885352 , 10.0978795 , 10.85500924, 10.1794367 ,
       10.04930678, 10.4533887 , 10.4619148 , 10.29001662, 10.37977593])

In [96]:
np.sin(a)

array([0.46411766, 0.83522136, 0.09772329, 0.75457698, 0.17847535,
       0.0492868 , 0.43801437, 0.44566305, 0.28596815, 0.37071238])

In [97]:
np.cos(a)

array([0.88577356, 0.54991389, 0.99521362, 0.65621154, 0.98394438,
       0.99878467, 0.89896797, 0.89520078, 0.95823912, 0.92874772])

In [98]:
np.sin(0)

0.0

In [99]:
np.sin(90)

0.8939966636005579

In [100]:
np.sin(180)

-0.8011526357338304

In [101]:
np.sin(360)

0.9589157234143065

# Questions
2 semester/terms in 10th standard,5 subjects
0,100
test_scores 0-100, 2x5
and then passing marks in 50
in how many subjects you passed in sem-1 and sem-2
anyone who failed in more than 2 subjects in a semester will be - FAILED and everyone else is PAAS

In [104]:
import random
import numpy as np


test_scores=np.random.randint(1,101,10)
fail=0
test_scores=test_scores.reshape(2,5)
print(test_scores)
for i in test_scores:

    for x in i:
        
    
        if x < 40:
          print('fail')
          fail=fail+1
          
print('You failed in '+str(fail)+' subjects')

[[ 8 40 49 21 39]
 [99  7 57 97 19]]
fail
fail
fail
fail
fail
You failed in 5 subjects


In [146]:
test_scores = np.random.randint(0, 100, (2, 5))

In [148]:
test_scores

array([[25, 96, 79, 23, 24],
       [ 0, 17, 72, 94, 76]])

In [147]:
# fail
np.sum(test_scores <50,axis=1) >2

array([ True, False])

In [149]:
#pass
np.sum(test_scores >50,axis=1) >2

array([False,  True])

In [123]:
import numpy as np

a=np.random.randint(1,100,(2,5),dtype=int)
print(a)
count = 0
for b in range(2):
  for i in range(5):
    print(a[b][i])
    if a[b][i] < 50:
      count = count +1
  print(count)
  if count>2:
    print("Failed")
    count=0
  else: 
    print("Pass")


[[70 92 85 65  9]
 [46 54  8 80 74]]
70
92
85
65
9
1
Pass
46
54
8
80
74
3
Failed


In [126]:
import numpy as np
test_scores = np.array(np.random.randint(0,100,10)).reshape(2,5)
print(test_scores)

print("Semester 1")
fail_count_1 = 0
for marks in test_scores[0]:
  if marks<50:
    fail_count_1 += 1
print("You failed in ", fail_count_1, " subjects.")
if (fail_count_1 > 2):
  print("You failed the semester")


print("Semester 2")
fail_count_2 = 0
for marks in test_scores[1]:
  if marks<50:
    fail_count_2 +=1
print("You failed in ", fail_count_2, " subjects")
if (fail_count_2> 2):
  print("You failed the semester")


[[50 28 12 86 71]
 [33  9 91 70 12]]
Semester 1
You failed in  2  subjects.
Semester 2
You failed in  3  subjects
You failed the semester


In [151]:
a=np.random.randint(1,10,5)
b=np.random.randint(1,10,5)

In [152]:
a

array([2, 4, 1, 7, 8])

In [153]:
b

array([5, 7, 6, 9, 6])

In [155]:
np.sum((a,b))

55

In [156]:
np.sum(a)

22

In [157]:
a.sum()

22

In [158]:
a=np.random.randint(1,10,(2,3))
b=np.random.randint(1,10,(2,3))

In [159]:
a

array([[2, 3, 1],
       [5, 4, 6]])

In [160]:
b

array([[2, 1, 8],
       [4, 8, 5]])

In [162]:
# row wise sum
np.sum(a,axis=1)

array([ 6, 15])

In [163]:
# column wise sum
np.sum(a,axis=0)

array([7, 7, 7])

In [164]:
a

array([[2, 3, 1],
       [5, 4, 6]])

In [165]:
np.subtract(a)

ValueError: invalid number of arguments

In [166]:
np.subtract(a,b)

array([[ 0,  2, -7],
       [ 1, -4,  1]])

In [167]:
b

array([[2, 1, 8],
       [4, 8, 5]])

In [168]:
a

array([[2, 3, 1],
       [5, 4, 6]])

In [169]:
np.subtract(b,a)

array([[ 0, -2,  7],
       [-1,  4, -1]])

In [170]:
np.subtract(10,3)

7

In [171]:
np.divide(a,b)

array([[1.   , 3.   , 0.125],
       [1.25 , 0.5  , 1.2  ]])

In [172]:
np.subtract(a,10)

array([[-8, -7, -9],
       [-5, -6, -4]])

In [173]:
np.divide(a)

ValueError: invalid number of arguments

In [175]:
np.divide(a,b,axis=1)

TypeError: 'axis' is an invalid keyword to ufunc 'true_divide'

In [176]:
np.divide(a,b)

array([[1.   , 3.   , 0.125],
       [1.25 , 0.5  , 1.2  ]])

In [177]:
a/b

array([[1.   , 3.   , 0.125],
       [1.25 , 0.5  , 1.2  ]])

In [178]:
a +b

array([[ 4,  4,  9],
       [ 9, 12, 11]])

In [181]:
np.sum((a,b),axis=0)

array([[ 4,  4,  9],
       [ 9, 12, 11]])

In [182]:
np.sum((a,b),axis=1)

array([[ 7,  7,  7],
       [ 6,  9, 13]])

In [183]:
a-b

array([[ 0,  2, -7],
       [ 1, -4,  1]])

In [184]:
np.subtract(a,b)

array([[ 0,  2, -7],
       [ 1, -4,  1]])

In [185]:
a.divide(b)

AttributeError: 'numpy.ndarray' object has no attribute 'divide'

In [186]:
a

array([[2, 3, 1],
       [5, 4, 6]])

In [187]:
b

array([[2, 1, 8],
       [4, 8, 5]])

In [188]:
np.sum((a,b),axis=0)

array([[ 4,  4,  9],
       [ 9, 12, 11]])

In [189]:
np.sum((a,b),axis=1)

array([[ 7,  7,  7],
       [ 6,  9, 13]])

In [190]:
a


array([[2, 3, 1],
       [5, 4, 6]])

In [191]:
b

array([[2, 1, 8],
       [4, 8, 5]])

In [192]:
np.sqrt(a)

array([[1.41421356, 1.73205081, 1.        ],
       [2.23606798, 2.        , 2.44948974]])

In [193]:
np.sqrt(25)

5.0

In [195]:
np.exp(a)

array([[  7.3890561 ,  20.08553692,   2.71828183],
       [148.4131591 ,  54.59815003, 403.42879349]])

In [196]:
np.exp(10)

22026.465794806718

In [197]:
np.min(a)

1

In [198]:
a

array([[2, 3, 1],
       [5, 4, 6]])

In [199]:
np.min(a,axis=0)

array([2, 3, 1])

In [200]:
np.min(a,axis=1)

array([1, 4])

In [201]:
np.median(np.array([1,2,3,4,5]))

3.0

In [202]:
np.mean(np.array([1,2,3,4,5]))

3.0

In [203]:
np.max(np.array([1,2,3,4,5]))

5

In [205]:
np.percentile(np.array([1,2,3,4,5]),q=50)

3.0

In [206]:
np.percentile(np.array([1,2,3,4,5]),q=10)

1.4

In [207]:
np.quantile(np.array([1,2,3,4,5]),q=1)

5

In [210]:

np.quantile(np.array([1,2,3,4,5]),q=0)

1

In [211]:
a

array([[2, 3, 1],
       [5, 4, 6]])

In [215]:
d=np.random.randint(1,100,(4,6))

In [216]:
d

array([[14, 95, 46, 59, 26,  7],
       [56, 94, 55, 65, 83, 26],
       [79, 64, 56, 64, 54, 62],
       [82, 84, 37,  8, 62, 34]])

In [217]:
d[2]

array([79, 64, 56, 64, 54, 62])

In [218]:
d[:2]

array([[14, 95, 46, 59, 26,  7],
       [56, 94, 55, 65, 83, 26]])

In [219]:
d[2:]

array([[79, 64, 56, 64, 54, 62],
       [82, 84, 37,  8, 62, 34]])

In [220]:
d

array([[14, 95, 46, 59, 26,  7],
       [56, 94, 55, 65, 83, 26],
       [79, 64, 56, 64, 54, 62],
       [82, 84, 37,  8, 62, 34]])

In [241]:
d[2:,2:]

array([[56, 64, 54, 62],
       [37,  8, 62, 34]])

In [235]:
d[[1,2],1:3]

array([[94, 55],
       [64, 56]])

In [221]:
d[0,1]

95

In [222]:
d[:2,1]

array([95, 94])

In [223]:
d[:2,1:]

array([[95, 46, 59, 26,  7],
       [94, 55, 65, 83, 26]])

In [242]:
a

array([[2, 3, 1],
       [5, 4, 6]])

In [243]:
b

array([[2, 1, 8],
       [4, 8, 5]])

In [244]:
np.concatenate((a,b))

array([[2, 3, 1],
       [5, 4, 6],
       [2, 1, 8],
       [4, 8, 5]])

In [245]:
np.concatenate((a,b),axis=1)

array([[2, 3, 1, 2, 1, 8],
       [5, 4, 6, 4, 8, 5]])

In [246]:
np.concatenate((a,b),axis=0)

array([[2, 3, 1],
       [5, 4, 6],
       [2, 1, 8],
       [4, 8, 5]])

In [247]:
np.hstack((a,b))

array([[2, 3, 1, 2, 1, 8],
       [5, 4, 6, 4, 8, 5]])

In [248]:
np.vstack((a,b))

array([[2, 3, 1],
       [5, 4, 6],
       [2, 1, 8],
       [4, 8, 5]])

In [249]:
np.column_stack((a,b))

array([[2, 3, 1, 2, 1, 8],
       [5, 4, 6, 4, 8, 5]])

In [250]:
c=np.random.randint(1,100,(3,3))

In [251]:
c

array([[19, 74, 78],
       [72, 19, 85],
       [60,  4, 42]])

In [252]:
a

array([[2, 3, 1],
       [5, 4, 6]])

In [255]:
np.vstack((a,c))

array([[ 2,  3,  1],
       [ 5,  4,  6],
       [19, 74, 78],
       [72, 19, 85],
       [60,  4, 42]])

In [254]:
np.hstack((a,c))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [256]:
a=10

In [258]:
print("hey" if a >10 else "You")

You
